clc; clear; close all;

[X, y] = training_data("abalone");

tic

svr = fitrsvm(X, y, ...
    'KernelFunction', 'rbf', ...
    'BoxConstraint', 1, ...
    'Epsilon', 0.05, ...
    'Solver', 'L1QP', ...
    'Standardize', true, ...
    'IterationLimit', 500);  

toc

y_pred = predict(svr, X);
disp(mse(y_pred, y));