clc; clear; close all;

[X, y] = training_data("abalone");

options = optimoptions('quadprog', ...
    'MaxIterations', 500, ...
    'OptimalityTolerance', 1e-6);

tic

svr = fitrsvm(X, y, ...
    'KernelFunction', 'rbf', ...
    'BoxConstraint', 1, ...
    'Epsilon', 0.1, ...
    'Solver', 'L1QP', ... 
    'Standardize', true, ...
    'Options', options);

toc

y_pred = predict(svr, X);
disp(mse(y_pred, y));



